# Generated by Django 4.2.7 on 2023-11-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
